#!/bin/bash

QUOTES=(
  "He who has a why to live can bear almost any how. — Nietzsche"
  "God is dead. God remains dead. And we have killed him. — Nietzsche"
  "Without music, life would be a mistake. — Nietzsche"
  "That which does not kill us makes us stronger. — Nietzsche"
  "Man is something that shall be overcome. What have you done to overcome him? — Nietzsche"
  "There are no facts, only interpretations. — Nietzsche"
  "In individuals, insanity is rare; but in groups, parties, nations and epochs, it is the rule. — Nietzsche"
  "The man who moves a mountain begins by carrying away small stones. — Confucius"
  "The question is not who is going to let me; it is who is going to stop me. — Ayn Rand"
  "The ladder of success is best climbed by stepping on the rungs of opportunity. — Ayn Rand"
  "I swear by my life and my love of it that I will never live for the sake of another man. — Ayn Rand"
  "The smallest minority on earth is the individual. — Ayn Rand"
  "A creative man is motivated by the desire to achieve, not by the desire to beat others. — Ayn Rand"
  "Do not let your fire go out. Do not let the hero in your soul perish. — Ayn Rand"
  "Talent hits a target no one else can hit; genius hits a target no one else can see. — Schopenhauer"
  "All truth passes through three stages: ridicule, violent opposition, acceptance. — Schopenhauer"
  "A man can be himself only so long as he is alone. — Schopenhauer"
  "Compassion is the basis of morality. — Schopenhauer"
  "The world is my representation. — Schopenhauer"
  "Great men are like eagles, and build their nest on some lofty solitude. — Schopenhauer"
  "Impossible is a word to be found only in the dictionary of fools. — Napoleon"
  "If you want a thing done well, do it yourself. — Napoleon"
  "The world suffers a lot. Not because of the violence of bad people, but because of the silence of good people. — Napoleon"
  "Courage is not having the strength to go on; it is going on when you do not have the strength. — Napoleon"
  "Death is nothing, but to live defeated and inglorious is to die daily. — Napoleon"
  "The strong man is the one who is able to intercept at will the communication between the senses and the mind. — Napoleon"
  "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light. — Plato"
  "The measure of a man is what he does with power. — Plato"
  "Wise men speak because they have something to say; fools because they have to say something. — Plato"
  "Be kind, for everyone you meet is fighting a hard battle. — Plato"
  "The first and greatest victory is to conquer yourself. — Plato"
  "Opinion is the medium between knowledge and ignorance. — Plato"
  "You have power over your mind, not outside events. Realize this, and you will find strength. — Marcus Aurelius"
  "The happiness of your life depends upon the quality of your thoughts. — Marcus Aurelius"
  "Waste no more time arguing about what a good man should be. Be one. — Marcus Aurelius"
  "It is not death that a man should fear, but he should fear never beginning to live. — Marcus Aurelius"
  "The soul becomes dyed with the colour of its thoughts. — Marcus Aurelius"
  "Very little is needed to make a happy life; it is all within yourself, in your way of thinking. — Marcus Aurelius"
  "When you arise in the morning, think of what a precious privilege it is to be alive. — Marcus Aurelius"
  "The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane. — Marcus Aurelius"
  "Accept the things to which fate binds you, and love the people with whom fate brings you together. — Marcus Aurelius"
  "If it is not right, do not do it; if it is not true, do not say it. — Marcus Aurelius"
  "No man is free who is not master of himself. — Epictetus"
  "It is the mark of an educated mind to be able to entertain a thought without accepting it. — Aristotle"
  "Knowing yourself is the beginning of all wisdom. — Aristotle"
  "I cannot teach anybody anything. I can only make them think. — Socrates"
  "The unexamined life is not worth living. — Socrates"
  "To live is to suffer, to survive is to find some meaning in the suffering. — Nietzsche"
  "Battle not with monsters, lest ye become a monster. — Nietzsche"
  "One must still have chaos in oneself to give birth to a dancing star. — Nietzsche"
  "History is written by the victors. — Napoleon"
)

# Pick a random quote
RANDOM_INDEX=$((RANDOM % ${#QUOTES[@]}))
QUOTE="${QUOTES[$RANDOM_INDEX]}"

sketchybar --set "$NAME" label="$QUOTE"
