#!/bin/bash

QUOTES=(
  "He who has a why to live can bear almost any how. — Nietzsche"
  "God is dead. God remains dead. And we have killed him. — Nietzsche"
  "Without music, life would be a mistake. — Nietzsche"
  "That which does not kill us makes us stronger. — Nietzsche"
  "Man is something that shall be overcome. What have you done to overcome him? — Nietzsche"
  "There are no facts, only interpretations. — Nietzsche"
  "In individuals, insanity is rare; but in groups, parties, nations and epochs, it is the rule. — Nietzsche"
  "The man who moves a mountain begins by carrying away small stones. — Confucius"
  "The question is not who is going to let me; it is who is going to stop me. — Ayn Rand"
  "The ladder of success is best climbed by stepping on the rungs of opportunity. — Ayn Rand"
  "I swear by my life and my love of it that I will never live for the sake of another man. — Ayn Rand"
  "The smallest minority on earth is the individual. — Ayn Rand"
  "A creative man is motivated by the desire to achieve, not by the desire to beat others. — Ayn Rand"
  "Do not let your fire go out. Do not let the hero in your soul perish. — Ayn Rand"
  "Talent hits a target no one else can hit; genius hits a target no one else can see. — Schopenhauer"
  "All truth passes through three stages: ridicule, violent opposition, acceptance. — Schopenhauer"
  "A man can be himself only so long as he is alone. — Schopenhauer"
  "Compassion is the basis of morality. — Schopenhauer"
  "The world is my representation. — Schopenhauer"
  "Great men are like eagles, and build their nest on some lofty solitude. — Schopenhauer"
  "Impossible is a word to be found only in the dictionary of fools. — Napoleon"
  "If you want a thing done well, do it yourself. — Napoleon"
  "The world suffers a lot. Not because of the violence of bad people, but because of the silence of good people. — Napoleon"
  "Courage is not having the strength to go on; it is going on when you do not have the strength. — Napoleon"
  "Death is nothing, but to live defeated and inglorious is to die daily. — Napoleon"
  "The strong man is the one who is able to intercept at will the communication between the senses and the mind. — Napoleon"
  "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light. — Plato"
  "The measure of a man is what he does with power. — Plato"
  "Wise men speak because they have something to say; fools because they have to say something. — Plato"
  "Be kind, for everyone you meet is fighting a hard battle. — Plato"
  "The first and greatest victory is to conquer yourself. — Plato"
  "Opinion is the medium between knowledge and ignorance. — Plato"
  "You have power over your mind, not outside events. Realize this, and you will find strength. — Marcus Aurelius"
  "The happiness of your life depends upon the quality of your thoughts. — Marcus Aurelius"
  "Waste no more time arguing about what a good man should be. Be one. — Marcus Aurelius"
  "It is not death that a man should fear, but he should fear never beginning to live. — Marcus Aurelius"
  "The soul becomes dyed with the colour of its thoughts. — Marcus Aurelius"
  "Very little is needed to make a happy life; it is all within yourself, in your way of thinking. — Marcus Aurelius"
  "When you arise in the morning, think of what a precious privilege it is to be alive. — Marcus Aurelius"
  "The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane. — Marcus Aurelius"
  "Accept the things to which fate binds you, and love the people with whom fate brings you together. — Marcus Aurelius"
  "If it is not right, do not do it; if it is not true, do not say it. — Marcus Aurelius"
  "No man is free who is not master of himself. — Epictetus"
  "It is the mark of an educated mind to be able to entertain a thought without accepting it. — Aristotle"
  "Knowing yourself is the beginning of all wisdom. — Aristotle"
  "I cannot teach anybody anything. I can only make them think. — Socrates"
  "The unexamined life is not worth living. — Socrates"
  "To live is to suffer, to survive is to find some meaning in the suffering. — Nietzsche"
  "Battle not with monsters, lest ye become a monster. — Nietzsche"
  "One must still have chaos in oneself to give birth to a dancing star. — Nietzsche"
  "History is written by the victors. — Napoleon"

  # Time, urgency, and mortality
  "Time is the most valuable thing a man can spend. — Theophrastus"
  "Lost time is never found again. — Benjamin Franklin"
  "The trouble is, you think you have time. — Buddha"
  "Time flies over us, but leaves its shadow behind. — Nathaniel Hawthorne"
  "They always say time changes things, but you actually have to change them yourself. — Andy Warhol"
  "The two most powerful warriors are patience and time. — Leo Tolstoy"
  "Time is what we want most, but what we use worst. — William Penn"
  "You may delay, but time will not. — Benjamin Franklin"
  "It is not that we have a short time to live, but that we waste a great deal of it. — Seneca"
  "While we are postponing, life speeds by. — Seneca"
  "Begin at once to live, and count each separate day as a separate life. — Seneca"
  "We suffer more in imagination than in reality. — Seneca"
  "Life is long if you know how to use it. — Seneca"
  "No man is free who is a slave to the flesh. — Seneca"
  "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult. — Seneca"
  "Luck is what happens when preparation meets opportunity. — Seneca"
  "As long as you live, keep learning how to live. — Seneca"
  "How long are you going to wait before you demand the best for yourself? — Epictetus"
  "Make the best use of what is in your power, and take the rest as it happens. — Epictetus"
  "First say to yourself what you would be; and then do what you have to do. — Epictetus"
  "Circumstances do not make the man, they reveal him. — Epictetus"
  "It is impossible for a man to learn what he thinks he already knows. — Epictetus"
  "Memento mori — Remember, you will die. — Stoic proverb"
  "Let us prepare our minds as if we had come to the very end of life. — Seneca"
  "You could leave life right now. Let that determine what you do and say and think. — Marcus Aurelius"
  "Think of yourself as dead. You have lived your life. Now, take what is left and live it properly. — Marcus Aurelius"
  "Do not act as if you had ten thousand years to live. Death hangs over you. While you live, while it is in your power, be good. — Marcus Aurelius"
  "Dwell on the beauty of life. Watch the stars, and see yourself running with them. — Marcus Aurelius"
  "The impediment to action advances action. What stands in the way becomes the way. — Marcus Aurelius"
  "Never esteem anything as of advantage to you that will make you break your word or lose your self-respect. — Marcus Aurelius"
  "How we spend our days is, of course, how we spend our lives. — Annie Dillard"

  # Fire, ambition, and relentless pursuit
  "A man who dares to waste one hour of time has not discovered the value of life. — Charles Darwin"
  "Do not go gentle into that good night. Rage, rage against the dying of the light. — Dylan Thomas"
  "Fate whispers to the warrior: You cannot withstand the storm. The warrior whispers back: I am the storm."
  "I am not what happened to me. I am what I choose to become. — Carl Jung"
  "Until you make the unconscious conscious, it will direct your life and you will call it fate. — Carl Jung"
  "Your vision will become clear only when you can look into your own heart. Who looks outside, dreams; who looks inside, awakes. — Carl Jung"
  "The privilege of a lifetime is to become who you truly are. — Carl Jung"
  "Thinking is difficult, that is why most people judge. — Carl Jung"
  "Every man dies. Not every man really lives. — William Wallace"
  "The world breaks everyone, and afterward, many are strong at the broken places. — Ernest Hemingway"
  "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self. — Ernest Hemingway"
  "The only way to deal with this life meaningfully is to find one's passion, and put everything into it. — Kierkegaard"
  "Life can only be understood backwards; but it must be lived forwards. — Kierkegaard"
  "Anxiety is the dizziness of freedom. — Kierkegaard"
  "People demand freedom of speech as a compensation for the freedom of thought which they seldom use. — Kierkegaard"
  "The greatest hazard of all, losing one's self, can occur very quietly, as if it were nothing at all. — Kierkegaard"
  "What does not destroy me, makes me stronger. — Nietzsche"
  "The snake which cannot cast its skin has to die. So do the minds which are prevented from changing their opinions. — Nietzsche"
  "You must have chaos within you to give birth to a dancing star. — Nietzsche"
  "There is always some madness in love. But there is also always some reason in madness. — Nietzsche"
  "Whoever fights monsters should see to it that in the process he does not become a monster. When you gaze into an abyss, the abyss also gazes into you. — Nietzsche"

  # Discipline, strength, and self-mastery
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Aristotle"
  "The energy of the mind is the essence of life. — Aristotle"
  "Discipline is the bridge between goals and accomplishment. — Jim Rohn"
  "Hard times create strong men. Strong men create good times. Good times create weak men. Weak men create hard times. — G. Michael Hopf"
  "The only person you are destined to become is the person you decide to be. — Ralph Waldo Emerson"
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson"
  "Do not go where the path may lead, go instead where there is no path and leave a trail. — Ralph Waldo Emerson"
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. — Ralph Waldo Emerson"
  "The mind is everything. What you think you become. — Buddha"
  "In the middle of difficulty lies opportunity. — Albert Einstein"
  "Great spirits have always encountered violent opposition from mediocre minds. — Albert Einstein"
  "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world. — Albert Einstein"
  "Insanity is doing the same thing over and over and expecting different results. — Albert Einstein"
  "The best time to plant a tree was 20 years ago. The second best time is now. — Chinese Proverb"
  "Fall seven times, stand up eight. — Japanese Proverb"
  "The wound is the place where the light enters you. — Rumi"
  "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself. — Rumi"
  "What you seek is seeking you. — Rumi"
  "Don't be satisfied with stories, how things have gone with others. Unfold your own myth. — Rumi"
  "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray. — Rumi"

  # Existential and deep philosophical
  "Man is condemned to be free; because once thrown into the world, he is responsible for everything he does. — Jean-Paul Sartre"
  "Freedom is what we do with what is done to us. — Jean-Paul Sartre"
  "Existence precedes essence. — Jean-Paul Sartre"
  "One must imagine Sisyphus happy. — Albert Camus"
  "In the depth of winter, I finally learned that within me there lay an invincible summer. — Albert Camus"
  "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion. — Albert Camus"
  "Real generosity towards the future lies in giving all to the present. — Albert Camus"
  "Should I kill myself, or have a cup of coffee? — Albert Camus"
  "I rebel; therefore I exist. — Albert Camus"
  "To dare is to lose one's footing momentarily. Not to dare is to lose oneself. — Kierkegaard"
  "Loneliness does not come from having no people around, but from being unable to communicate the things that seem important to oneself. — Carl Jung"
  "The cave you fear to enter holds the treasure you seek. — Joseph Campbell"
  "A ship in harbor is safe, but that is not what ships are built for. — John A. Shedd"
  "If you are not willing to risk the unusual, you will have to settle for the ordinary. — Jim Rohn"
  "Your time is limited. Do not waste it living someone else's life. — Steve Jobs"
  "Stay hungry. Stay foolish. — Steve Jobs"
  "The graveyard is the richest place on earth, full of unwritten novels, unfinished masterpieces, and unfulfilled dreams. — Les Brown"
  "Most people overestimate what they can do in one year and underestimate what they can do in ten years. — Bill Gates"
  "The mass of men lead lives of quiet desperation. — Henry David Thoreau"
  "I went to the woods because I wished to live deliberately, to front only the essential facts of life. — Henry David Thoreau"
  "Our life is frittered away by detail. Simplify, simplify. — Henry David Thoreau"
  "Time is a created thing. To say I don't have time is to say I don't want to. — Lao Tzu"
  "The journey of a thousand miles begins with a single step. — Lao Tzu"
  "When I let go of what I am, I become what I might be. — Lao Tzu"
  "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power. — Lao Tzu"
  "Nature does not hurry, yet everything is accomplished. — Lao Tzu"
)

# Pick a random quote
RANDOM_INDEX=$((RANDOM % ${#QUOTES[@]}))
QUOTE="${QUOTES[$RANDOM_INDEX]}"

sketchybar --set "$NAME" label="$QUOTE"
